# Use an official Python runtime as a parent image
FROM python:3.7.4

# Set the working directory to /app
WORKDIR /swagger-ui

# Copy the current directory contents into the container at /app
COPY . /swagger-ui
COPY ./route/ /swagger-ui/route
COPY ./static/ /swagger-ui/static

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD ["ls"]
CMD ["python", "app.py"]